export type UserRole =
  | "member"
  | "coordinator"
  | "president"
  | "franchise"
  | "hq_admin"
  | "super_admin";
export type DemoUser = {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  avatar: string;
  city: string;
  company: string;
  profession: string;
  plan: string;
  reputation: number;
  chapter: string;
  connections: number;
  pending: number;
  given: number;
  received: number;
};

export const DEMO_USERS: DemoUser[] = [
  {
    id: "u1",
    name: "Arjun Mehta",
    email: "member@nia.com",
    role: "member",
    avatar: "AM",
    city: "Mumbai",
    company: "Mehta Exports Pvt Ltd",
    profession: "Manufacturer & Exporter",
    plan: "pro",
    reputation: 780,
    chapter: "Mumbai South",
    connections: 24,
    pending: 3,
    given: 12,
    received: 8,
  },
  {
    id: "u2",
    name: "Priya Sharma",
    email: "coord@nia.com",
    role: "coordinator",
    avatar: "PS",
    city: "Bangalore",
    company: "BizConnect Solutions",
    profession: "Chapter Coordinator",
    plan: "pro",
    reputation: 1120,
    chapter: "Bangalore Central",
    connections: 68,
    pending: 5,
    given: 34,
    received: 29,
  },
  {
    id: "u6",
    name: "Vikram Nair",
    email: "president@nia.com",
    role: "president",
    avatar: "VN",
    city: "Mumbai",
    company: "Nair Industries",
    profession: "Chapter President",
    plan: "pro",
    reputation: 1680,
    chapter: "Mumbai South",
    connections: 94,
    pending: 2,
    given: 56,
    received: 48,
  },
  {
    id: "u3",
    name: "Rajesh Gupta",
    email: "franchise@nia.com",
    role: "franchise",
    avatar: "RG",
    city: "Delhi",
    company: "Gupta Holdings",
    profession: "Franchise Owner",
    plan: "teams",
    reputation: 2240,
    chapter: "Delhi NCR",
    connections: 142,
    pending: 11,
    given: 89,
    received: 72,
  },
  {
    id: "u4",
    name: "Kavita Patel",
    email: "hq@nia.com",
    role: "hq_admin",
    avatar: "KP",
    city: "Ahmedabad",
    company: "NIA One HQ",
    profession: "HQ Administrator",
    plan: "teams",
    reputation: 9800,
    chapter: "HQ",
    connections: 512,
    pending: 0,
    given: 0,
    received: 0,
  },
  {
    id: "u5",
    name: "Super Admin",
    email: "super@nia.com",
    role: "super_admin",
    avatar: "SA",
    city: "Pan India",
    company: "NIA One",
    profession: "Super Admin",
    plan: "teams",
    reputation: 9999,
    chapter: "HQ",
    connections: 999,
    pending: 0,
    given: 0,
    received: 0,
  },
];

export const MEMBERS = [
  {
    id: "m1",
    name: "Ravi Kumar",
    company: "TechSoft India",
    profession: "IT Services",
    city: "Pune",
    avatar: "RK",
    color: "#6366f1",
    tags: ["Tech", "B2B", "SaaS"],
    connections: 45,
    verified: true,
    reputation: 620,
    bio: "15 years in enterprise IT. Cloud migrations and ERP implementations.",
  },
  {
    id: "m2",
    name: "Sneha Joshi",
    company: "Joshi Textiles",
    profession: "Textile Manufacturer",
    city: "Surat",
    avatar: "SJ",
    color: "#ec4899",
    tags: ["Manufacturing", "Export"],
    connections: 28,
    verified: true,
    reputation: 480,
    bio: "3rd gen textile manufacturer. Export to 12 countries.",
  },
  {
    id: "m3",
    name: "Vikram Singh",
    company: "Singh Builders",
    profession: "Real Estate Developer",
    city: "Delhi",
    avatar: "VS",
    color: "#f59e0b",
    tags: ["Real Estate", "Construction"],
    connections: 67,
    verified: false,
    reputation: 710,
    bio: "Commercial & residential projects across NCR. 200+ units delivered.",
  },
  {
    id: "m4",
    name: "Anita Rao",
    company: "Rao & Associates",
    profession: "CA & Financial Advisor",
    city: "Hyderabad",
    avatar: "AR",
    color: "#10b981",
    tags: ["Finance", "CA", "Tax"],
    connections: 89,
    verified: true,
    reputation: 840,
    bio: "Chartered Accountant 18 years. GST, tax planning, audit.",
  },
  {
    id: "m5",
    name: "Mohit Agarwal",
    company: "Agarwal Foods",
    profession: "FMCG Distributor",
    city: "Jaipur",
    avatar: "MA",
    color: "#8b5cf6",
    tags: ["FMCG", "Retail"],
    connections: 34,
    verified: true,
    reputation: 560,
    bio: "Pan-Rajasthan FMCG network. 500+ retail touchpoints.",
  },
  {
    id: "m6",
    name: "Neha Tiwari",
    company: "DigitalEdge Agency",
    profession: "Digital Marketing",
    city: "Mumbai",
    avatar: "NT",
    color: "#ef4444",
    tags: ["Marketing", "Digital", "SEO"],
    connections: 52,
    verified: true,
    reputation: 690,
    bio: "Full-service digital agency. Google Partner. 80+ brands.",
  },
  {
    id: "m7",
    name: "Rohit Verma",
    company: "Verma Logistics",
    profession: "Logistics",
    city: "Chennai",
    avatar: "RV",
    color: "#14b8a6",
    tags: ["Logistics", "Supply Chain"],
    connections: 41,
    verified: false,
    reputation: 430,
    bio: "Pan-India logistics. Cold chain specialists. 200+ vehicles.",
  },
  {
    id: "m8",
    name: "Deepa Nair",
    company: "Nair Legal LLP",
    profession: "Corporate Lawyer",
    city: "Kochi",
    avatar: "DN",
    color: "#f97316",
    tags: ["Legal", "Corporate", "IP"],
    connections: 38,
    verified: true,
    reputation: 590,
    bio: "Corporate law, M&A, IP protection, startup advisory.",
  },
  {
    id: "m9",
    name: "Suresh Iyer",
    company: "Iyer Pharma",
    profession: "Pharma Distributor",
    city: "Chennai",
    avatar: "SI",
    color: "#0ea5e9",
    tags: ["Pharma", "Healthcare"],
    connections: 61,
    verified: true,
    reputation: 730,
    bio: "South India pharma distribution. 22 years. 800+ pharmacy network.",
  },
  {
    id: "m10",
    name: "Pooja Malhotra",
    company: "Malhotra Events",
    profession: "Event Management",
    city: "Mumbai",
    avatar: "PM",
    color: "#a855f7",
    tags: ["Events", "Hospitality"],
    connections: 77,
    verified: true,
    reputation: 810,
    bio: "Premium corporate events and destination weddings.",
  },
  {
    id: "m11",
    name: "Amit Shah",
    company: "Shah Solar",
    profession: "Solar Energy",
    city: "Ahmedabad",
    avatar: "AS",
    color: "#22c55e",
    tags: ["Solar", "Energy"],
    connections: 29,
    verified: true,
    reputation: 510,
    bio: "Rooftop solar EPC contractor. 10MW+ installed.",
  },
  {
    id: "m12",
    name: "Rekha Menon",
    company: "Menon Exports",
    profession: "Spice Exporter",
    city: "Kochi",
    avatar: "RM",
    color: "#f43f5e",
    tags: ["Export", "Spices"],
    connections: 44,
    verified: true,
    reputation: 640,
    bio: "Kerala spice exporter. 25+ years. Organic certified.",
  },
];

export const REFERRALS = [
  {
    id: "r1",
    title: "Website Development for Retail Brand",
    client: "StyleCo Pvt Ltd",
    clientEmail: "ceo@styleco.in",
    clientPhone: "+91 98765 43210",
    budget: "₹2,50,000",
    urgency: "High",
    category: "IT Services",
    status: "Won",
    referredTo: "Ravi Kumar",
    referredBy: "Arjun Mehta",
    date: "Mar 15, 2026",
    value: 250000,
    notes: "Full e-commerce site with mobile app. D2C fashion brand.",
    timeline: [
      { date: "Mar 15", event: "Referral Created" },
      { date: "Mar 16", event: "Accepted by Ravi" },
      { date: "Mar 18", event: "Initial Call Done" },
      { date: "Mar 22", event: "Proposal Sent – ₹2.5L" },
      { date: "Apr 2", event: "Deal Won! 🎉" },
    ],
  },
  {
    id: "r2",
    title: "Export Insurance for Textile Shipment",
    client: "XYZ Textiles",
    clientEmail: "cfo@xyztextiles.com",
    clientPhone: "+91 99001 12345",
    budget: "₹50,000",
    urgency: "Medium",
    category: "Finance",
    status: "Contacted",
    referredTo: "Anita Rao",
    referredBy: "Sneha Joshi",
    date: "Apr 1, 2026",
    value: 50000,
    notes: "Annual marine cargo insurance for 12-country export operation.",
    timeline: [
      { date: "Apr 1", event: "Referral Created" },
      { date: "Apr 2", event: "Accepted by Anita" },
      { date: "Apr 5", event: "Client Contacted" },
    ],
  },
  {
    id: "r3",
    title: "Commercial Office Space – 5000 sqft",
    client: "StartupHub India",
    clientEmail: "ops@startuphub.in",
    clientPhone: "+91 98100 55432",
    budget: "₹80,000/mo",
    urgency: "Low",
    category: "Real Estate",
    status: "Proposal Sent",
    referredTo: "Vikram Singh",
    referredBy: "Arjun Mehta",
    date: "Apr 10, 2026",
    value: 80000,
    notes: "Plug-and-play office space in south Delhi.",
    timeline: [
      { date: "Apr 10", event: "Referral Created" },
      { date: "Apr 11", event: "Accepted" },
      { date: "Apr 14", event: "Site Visit Arranged" },
      { date: "Apr 17", event: "Proposal Sent" },
    ],
  },
  {
    id: "r4",
    title: "GST Audit & Annual Filing",
    client: "Patel Traders",
    clientEmail: "accounts@pateltrade.com",
    clientPhone: "+91 97654 32100",
    budget: "₹25,000",
    urgency: "High",
    category: "CA / Finance",
    status: "New",
    referredTo: "Anita Rao",
    referredBy: "Mohit Agarwal",
    date: "Apr 19, 2026",
    value: 25000,
    notes: "FY2025-26 GST audit + ITR filing. Turnover ~₹8Cr.",
    timeline: [{ date: "Apr 19", event: "Referral Created" }],
  },
  {
    id: "r5",
    title: "Digital Marketing – 6 Month Retainer",
    client: "NewBrand Fashion",
    clientEmail: "marketing@newbrand.in",
    clientPhone: "+91 98200 66781",
    budget: "₹40,000/mo",
    urgency: "Medium",
    category: "Marketing",
    status: "Lost",
    referredTo: "Neha Tiwari",
    referredBy: "Arjun Mehta",
    date: "Feb 20, 2026",
    value: 40000,
    notes: "Client chose a cheaper agency. Follow up in Q3.",
    timeline: [
      { date: "Feb 20", event: "Referral Created" },
      { date: "Feb 21", event: "Accepted" },
      { date: "Feb 25", event: "Proposal Sent" },
      { date: "Mar 10", event: "Lost – Budget Constraint" },
    ],
  },
  {
    id: "r6",
    title: "ERP Software License & Implementation",
    client: "MegaCorp Industries",
    clientEmail: "cio@megacorp.in",
    clientPhone: "+91 99100 77890",
    budget: "₹1,20,000",
    urgency: "High",
    category: "IT Services",
    status: "Completed",
    referredTo: "Ravi Kumar",
    referredBy: "Rajesh Gupta",
    date: "Jan 5, 2026",
    value: 120000,
    notes: "SAP B1 implementation for 200-user manufacturing firm.",
    timeline: [
      { date: "Jan 5", event: "Referral Created" },
      { date: "Jan 6", event: "Accepted" },
      { date: "Jan 20", event: "Proposal Sent" },
      { date: "Feb 1", event: "Won" },
      { date: "Mar 30", event: "Completed ✅" },
    ],
  },
  {
    id: "r7",
    title: "Solar Rooftop – Factory 500kW",
    client: "Gujarat Ceramics Ltd",
    clientEmail: "plant@gjceram.in",
    clientPhone: "+91 98765 00123",
    budget: "₹1,80,00,000",
    urgency: "Medium",
    category: "Solar Energy",
    status: "Accepted",
    referredTo: "Amit Shah",
    referredBy: "Rajesh Gupta",
    date: "Apr 12, 2026",
    value: 18000000,
    notes: "Large industrial solar installation. Factory has 2-acre flat roof.",
    timeline: [
      { date: "Apr 12", event: "Referral Created" },
      { date: "Apr 13", event: "Accepted by Amit" },
    ],
  },
];

export const CHAPTERS = [
  {
    id: "c1",
    name: "Mumbai South",
    city: "Mumbai",
    state: "Maharashtra",
    members: 42,
    capacity: 50,
    coordinator: "Priya Sharma",
    president: "Vivek Nair",
    meetings: 52,
    attendance: 87,
    openSeats: 5,
    status: "active",
    category: "Metro",
    revenue: "₹18.5L",
    established: "Jan 2020",
  },
  {
    id: "c2",
    name: "Bangalore Central",
    city: "Bangalore",
    state: "Karnataka",
    members: 38,
    capacity: 50,
    coordinator: "Suresh Kumar",
    president: "Meena Rao",
    meetings: 48,
    attendance: 82,
    openSeats: 8,
    status: "active",
    category: "Metro",
    revenue: "₹15.2L",
    established: "Jun 2020",
  },
  {
    id: "c3",
    name: "Delhi NCR",
    city: "Delhi",
    state: "Delhi",
    members: 55,
    capacity: 60,
    coordinator: "Meena Gupta",
    president: "Rohit Arora",
    meetings: 60,
    attendance: 79,
    openSeats: 2,
    status: "active",
    category: "Metro",
    revenue: "₹24.8L",
    established: "Sep 2019",
  },
  {
    id: "c4",
    name: "Pune West",
    city: "Pune",
    state: "Maharashtra",
    members: 29,
    capacity: 45,
    coordinator: "Ajay Patil",
    president: "Sunita Kulkarni",
    meetings: 40,
    attendance: 75,
    openSeats: 12,
    status: "active",
    category: "Tier-1",
    revenue: "₹10.4L",
    established: "Mar 2021",
  },
  {
    id: "c5",
    name: "Jaipur Pink City",
    city: "Jaipur",
    state: "Rajasthan",
    members: 22,
    capacity: 40,
    coordinator: "Radha Sharma",
    president: "Amit Jain",
    meetings: 32,
    attendance: 70,
    openSeats: 18,
    status: "new",
    category: "Tier-2",
    revenue: "₹6.1L",
    established: "Jan 2026",
  },
  {
    id: "c6",
    name: "Hyderabad Tech",
    city: "Hyderabad",
    state: "Telangana",
    members: 47,
    capacity: 50,
    coordinator: "Pradeep Reddy",
    president: "Kavitha Reddy",
    meetings: 56,
    attendance: 91,
    openSeats: 3,
    status: "active",
    category: "Metro",
    revenue: "₹21.3L",
    established: "Apr 2020",
  },
  {
    id: "c7",
    name: "Ahmedabad Business",
    city: "Ahmedabad",
    state: "Gujarat",
    members: 33,
    capacity: 45,
    coordinator: "Hiral Shah",
    president: "Kalpesh Mehta",
    meetings: 44,
    attendance: 83,
    openSeats: 9,
    status: "active",
    category: "Tier-1",
    revenue: "₹12.7L",
    established: "Nov 2020",
  },
  {
    id: "c8",
    name: "Kochi Seaport",
    city: "Kochi",
    state: "Kerala",
    members: 18,
    capacity: 35,
    coordinator: "Thomas Mathew",
    president: "Lina Joseph",
    meetings: 24,
    attendance: 68,
    openSeats: 17,
    status: "new",
    category: "Tier-2",
    revenue: "₹4.3L",
    established: "Mar 2026",
  },
];

export const EVENTS = [
  {
    id: "e1",
    title: "Business Mixer – Mumbai Spring Edition",
    date: "Apr 28, 2026",
    time: "6:00 PM",
    venue: "The Grand Hyatt, Mumbai",
    type: "Mixer",
    seats: 120,
    booked: 108,
    status: "upcoming",
    city: "Mumbai",
    price: 500,
    description:
      "Premium networking mixer with 100+ business leaders. Cocktails, canapes & connections.",
    speakers: ["Rajesh Sharma – TiE Mumbai", "Priya Mehta – FICCI Women"],
    tags: ["Networking", "Social"],
  },
  {
    id: "e2",
    title: "NIA Leadership Summit 2026",
    date: "May 15, 2026",
    time: "9:00 AM",
    venue: "Leela Palace, Bangalore",
    type: "Summit",
    seats: 300,
    booked: 245,
    status: "upcoming",
    city: "Bangalore",
    price: 2500,
    description:
      "Annual summit for chapter leaders, franchise owners, and top performers.",
    speakers: [
      "Nandan Nilekani – Keynote",
      "Kiran Mazumdar Shaw – Special Address",
    ],
    tags: ["Leadership", "Strategy"],
  },
  {
    id: "e3",
    title: "NIA Annual Convention 2026",
    date: "Jun 1, 2026",
    time: "10:00 AM",
    venue: "India Expo Centre, Greater Noida",
    type: "Convention",
    seats: 1000,
    booked: 672,
    status: "upcoming",
    city: "Delhi",
    price: 1500,
    description:
      "India's largest business networking convention. 1000+ members, 50+ speakers, awards night.",
    speakers: ["Multiple Keynotes", "Panel Discussions", "Awards Ceremony"],
    tags: ["Convention", "Awards"],
  },
  {
    id: "e4",
    title: "Chapter Presidents Meet Q1",
    date: "Mar 10, 2026",
    time: "2:00 PM",
    venue: "Pune Club, Pune",
    type: "Meeting",
    seats: 40,
    booked: 38,
    status: "completed",
    city: "Pune",
    price: 0,
    description: "Quarterly strategic review for all chapter presidents.",
    speakers: [],
    tags: ["Internal", "Strategy"],
  },
  {
    id: "e5",
    title: "Digital Marketing Workshop",
    date: "May 5, 2026",
    time: "10:00 AM",
    venue: "ITC Grand, Chennai",
    type: "Workshop",
    seats: 80,
    booked: 61,
    status: "upcoming",
    city: "Chennai",
    price: 799,
    description:
      "Half-day workshop on D2C growth, performance marketing, and AI tools.",
    speakers: ["Neha Tiwari – DigitalEdge"],
    tags: ["Workshop", "Marketing"],
  },
];

export const MEETINGS = [
  {
    id: "mt1",
    chapter: "Mumbai South",
    date: "Tue, Apr 22",
    time: "7:30 AM",
    venue: "Hotel Trident, Nariman Point",
    attendees: 38,
    max: 42,
    type: "Weekly",
    agenda: [
      "Roll Call & Attendance",
      "Member Spotlight – Arjun Mehta",
      "Referral Round (20 min)",
      "Visitor Introductions",
      "Announcements",
    ],
    status: "upcoming",
  },
  {
    id: "mt2",
    chapter: "Bangalore Central",
    date: "Wed, Apr 23",
    time: "8:00 AM",
    venue: "ITC Gardenia, Residency Road",
    attendees: 31,
    max: 38,
    type: "Weekly",
    agenda: [
      "New Member Welcome",
      "Education Slot – Digital Marketing",
      "Referral Round",
      "Business Card Exchange",
    ],
    status: "upcoming",
  },
  {
    id: "mt3",
    chapter: "Delhi NCR",
    date: "Fri, Apr 25",
    time: "7:00 AM",
    venue: "The Taj Mahal Hotel, New Delhi",
    attendees: 48,
    max: 55,
    type: "Weekly",
    agenda: [
      "Annual Role Elections",
      "Performance Review Q1",
      "Top Referrer Awards",
      "Strategic Planning 2026-27",
    ],
    status: "upcoming",
  },
  {
    id: "mt4",
    chapter: "Mumbai South",
    date: "Tue, Apr 15",
    time: "7:30 AM",
    venue: "Hotel Trident, Nariman Point",
    attendees: 40,
    max: 42,
    type: "Weekly",
    agenda: ["Regular weekly meeting"],
    status: "completed",
    referrals: 14,
    visitors: 3,
  },
];

export const LEARNING = [
  {
    id: "lc1",
    title: "Mastering Business Referral Networking",
    cat: "Networking",
    instructor: "Dr. Rajesh Nair",
    duration: "4h 30m",
    lessons: 18,
    enrolled: 1240,
    rating: 4.8,
    price: 0,
    emoji: "📡",
    progress: 65,
  },
  {
    id: "lc2",
    title: "Public Speaking for Business Leaders",
    cat: "Leadership",
    instructor: "Preethi Menon",
    duration: "6h 15m",
    lessons: 24,
    enrolled: 890,
    rating: 4.9,
    price: 1999,
    emoji: "🎤",
    progress: 0,
  },
  {
    id: "lc3",
    title: "Digital Marketing Masterclass 2026",
    cat: "Marketing",
    instructor: "Alok Mathur",
    duration: "8h 00m",
    lessons: 32,
    enrolled: 2100,
    rating: 4.7,
    price: 2999,
    emoji: "📱",
    progress: 20,
  },
  {
    id: "lc4",
    title: "GST & Tax Planning – FY 2026-27",
    cat: "Finance",
    instructor: "CA Sunita Krishnan",
    duration: "5h 00m",
    lessons: 20,
    enrolled: 760,
    rating: 4.6,
    price: 1499,
    emoji: "💼",
    progress: 100,
  },
  {
    id: "lc5",
    title: "AI Tools for Business Productivity",
    cat: "AI for Business",
    instructor: "Vikram Anand",
    duration: "3h 45m",
    lessons: 15,
    enrolled: 3400,
    rating: 4.9,
    price: 0,
    emoji: "🤖",
    progress: 30,
  },
  {
    id: "lc6",
    title: "Export Business – Start to Scale",
    cat: "Business",
    instructor: "Sunita Mehta",
    duration: "7h 20m",
    lessons: 28,
    enrolled: 580,
    rating: 4.5,
    price: 3499,
    emoji: "🚢",
    progress: 0,
  },
];

export const TRAVEL = [
  {
    id: "tp1",
    user: "Ravi Kumar",
    avatar: "RK",
    color: "#6366f1",
    from: "Pune",
    to: "Mumbai",
    dates: "Apr 24–26",
    purpose: "Client Meetings",
    lookingFor: "Introductions to CIOs & IT decision-makers",
    posted: "2 days ago",
  },
  {
    id: "tp2",
    user: "Anita Rao",
    avatar: "AR",
    color: "#10b981",
    from: "Hyderabad",
    to: "Bangalore",
    dates: "May 2–4",
    purpose: "FINSEC Conference",
    lookingFor: "Co-working space + evening networking dinners",
    posted: "5 days ago",
  },
  {
    id: "tp3",
    user: "Mohit Agarwal",
    avatar: "MA",
    color: "#8b5cf6",
    from: "Jaipur",
    to: "Delhi",
    dates: "Apr 28–30",
    purpose: "Trade Fair – India FMCG Expo",
    lookingFor: "Distributors and modern retail buyers",
    posted: "1 day ago",
  },
  {
    id: "tp4",
    user: "Deepa Nair",
    avatar: "DN",
    color: "#f97316",
    from: "Kochi",
    to: "Mumbai",
    dates: "May 10–12",
    purpose: "Client Acquisition",
    lookingFor: "Startup founders needing corporate legal advisory",
    posted: "3 days ago",
  },
  {
    id: "tp5",
    user: "Suresh Iyer",
    avatar: "SI",
    color: "#0ea5e9",
    from: "Chennai",
    to: "Hyderabad",
    dates: "May 5–7",
    purpose: "Pharma Conference",
    lookingFor: "Hospital admins & pharmacy chain owners",
    posted: "Today",
  },
];

export const BIZ_HUB = [
  {
    id: "bh1",
    title: "Need CA for Annual GST Audit",
    type: "Need CA",
    budget: "₹25,000",
    urgency: "High",
    city: "Mumbai",
    cat: "Finance",
    desc: "Mid-size trading company. FY26 GST audit + ITR filing. Turnover ~₹8Cr.",
    responses: 4,
    posted: "Apr 18",
  },
  {
    id: "bh2",
    title: "Seeking Seed Investor – EdTech Startup",
    type: "Need Investor",
    budget: "₹50L – 2Cr",
    urgency: "Medium",
    city: "Bangalore",
    cat: "Investment",
    desc: "EdTech startup with 2,000 paying users. MRR ₹4.2L. Seeking angel/seed investor.",
    responses: 11,
    posted: "Apr 15",
  },
  {
    id: "bh3",
    title: "Full-Stack Website + Mobile App",
    type: "Need Agency",
    budget: "₹1,50,000",
    urgency: "Low",
    city: "Pune",
    cat: "IT Services",
    desc: "D2C fashion brand needs e-commerce website + iOS/Android app.",
    responses: 7,
    posted: "Apr 12",
  },
  {
    id: "bh4",
    title: "Hiring – North India Sales Manager",
    type: "Hiring",
    budget: "₹8–12L CTC",
    urgency: "High",
    city: "Delhi",
    cat: "HR & Recruitment",
    desc: "B2B SaaS company. Need Sales Manager for North India. 5+ years experience.",
    responses: 3,
    posted: "Apr 19",
  },
  {
    id: "bh5",
    title: "Partnership – Pan-India FMCG Distribution",
    type: "Partnership",
    budget: "Revenue Share",
    urgency: "Medium",
    city: "Jaipur",
    cat: "Business Development",
    desc: "Rajasthan FMCG brand looking for distribution partners in Maharashtra, Gujarat, MP.",
    responses: 9,
    posted: "Apr 10",
  },
  {
    id: "bh6",
    title: "Need Corporate Legal Advisor",
    type: "Need Lawyer",
    budget: "₹15,000/mo retainer",
    urgency: "Low",
    city: "Kochi",
    cat: "Legal",
    desc: "Fast-growing startup needs corporate lawyer for contracts, IP, and compliance.",
    responses: 2,
    posted: "Apr 17",
  },
];

export const MESSAGES_DATA = [
  {
    id: "msg1",
    from: "Ravi Kumar",
    avatar: "RK",
    color: "#6366f1",
    msgs: [
      {
        from: "them",
        text: "Hi Arjun! Thanks for the referral. StyleCo seems like a great fit. Can we connect this week?",
        time: "10:42 AM",
      },
      {
        from: "me",
        text: "Hey Ravi! Absolutely. How does Thursday 4pm work for you?",
        time: "10:45 AM",
      },
      {
        from: "them",
        text: "Thursday 4pm works perfectly. I'll send a Google Meet link.",
        time: "10:47 AM",
      },
    ],
    unread: 0,
    lastTime: "10:47 AM",
  },
  {
    id: "msg2",
    from: "Anita Rao",
    avatar: "AR",
    color: "#10b981",
    msgs: [
      {
        from: "them",
        text: "Arjun, I received the referral for Patel Traders. Will reach out to them tomorrow. Thanks!",
        time: "Yesterday",
      },
    ],
    unread: 1,
    lastTime: "Yesterday",
  },
  {
    id: "msg3",
    from: "NIA Events Team",
    avatar: "NE",
    color: "#FF5C35",
    msgs: [
      {
        from: "them",
        text: "🎉 Business Mixer Mumbai – Only 12 seats left! Register now before it fills up.",
        time: "Apr 19",
      },
    ],
    unread: 1,
    lastTime: "Apr 19",
  },
  {
    id: "msg4",
    from: "Vikram Singh",
    avatar: "VS",
    color: "#f59e0b",
    msgs: [
      {
        from: "them",
        text: "Thanks for the referral brother. StartupHub visit went well – proposal sent.",
        time: "Apr 18",
      },
      { from: "me", text: "Great! Keep me posted 🤞", time: "Apr 18" },
    ],
    unread: 0,
    lastTime: "Apr 18",
  },
  {
    id: "msg5",
    from: "NIA Chapter Bot",
    avatar: "NC",
    color: "#8b5cf6",
    msgs: [
      {
        from: "them",
        text: "📅 Reminder: Mumbai South weekly meeting tomorrow at 7:30 AM. Hotel Trident, Nariman Point.",
        time: "Apr 20",
      },
    ],
    unread: 1,
    lastTime: "Apr 20",
  },
];

export const PAYMENTS_DATA = [
  {
    id: "p1",
    desc: "Annual Membership – Pro Plan",
    amount: "₹12,000",
    date: "Apr 1, 2026",
    status: "Paid",
    type: "Membership",
    invoice: "INV-2026-001",
  },
  {
    id: "p2",
    desc: "Event Ticket – Leadership Summit 2026",
    amount: "₹2,500",
    date: "Mar 25, 2026",
    status: "Paid",
    type: "Event",
    invoice: "INV-2026-002",
  },
  {
    id: "p3",
    desc: "Annual Membership – Renewal FY25",
    amount: "₹12,000",
    date: "Apr 1, 2025",
    status: "Paid",
    type: "Membership",
    invoice: "INV-2025-001",
  },
  {
    id: "p4",
    desc: "Event Ticket – Annual Convention 2025",
    amount: "₹1,500",
    date: "May 28, 2025",
    status: "Paid",
    type: "Event",
    invoice: "INV-2025-022",
  },
  {
    id: "p5",
    desc: "Learning Course – Public Speaking",
    amount: "₹1,999",
    date: "Feb 12, 2026",
    status: "Paid",
    type: "Course",
    invoice: "INV-2026-003",
  },
  {
    id: "p6",
    desc: "Mumbai Mixer Registration",
    amount: "₹500",
    date: "Apr 20, 2026",
    status: "Pending",
    type: "Event",
    invoice: "INV-2026-004",
  },
];

export const RB_DEMO = [
  {
    input:
      "We will think about your proposal and get back to you by end of next week.",
    type: "Message Analyser",
    power: 35,
    intent:
      "Soft rejection. The sender is likely not interested but avoiding direct confrontation. 'Think about it' + vague timeline = classic delay tactic.",
    emotion: ["Disinterest", "Politeness", "Avoidance"],
    manipulation: ["Vague Timeline", "Non-committal language"],
    strategies: [
      {
        label: "Soft",
        icon: "🤝",
        text: "Thanks for considering! If it helps, I can share a quick case study. Happy to hop on a 10-min call at your convenience.",
      },
      {
        label: "Direct",
        icon: "🎯",
        text: "Understood. The offer is valid until Friday. After that I'll need to move to the next client. Can we confirm either way?",
      },
      {
        label: "Firm",
        icon: "⚡",
        text: "I need to close my schedule this week. Are you in or out? Happy to answer any blockers right now.",
      },
    ],
  },
  {
    input:
      "No worries at all, take your time. There's really no rush on our end.",
    type: "Message Analyser",
    power: 65,
    intent:
      "The sender holds leverage and is deliberately projecting calm. This signals they have alternatives. 'No worries' + 'no rush' from a power position = subtle pressure.",
    emotion: ["Calm", "Confidence", "Subtle Pressure"],
    manipulation: ["False Casualness", "Scarcity Signal"],
    strategies: [
      {
        label: "Soft",
        icon: "🤝",
        text: "Thanks for being flexible! I'll have everything ready by Thursday – want to do a quick sync then?",
      },
      {
        label: "Direct",
        icon: "🎯",
        text: "Appreciate the patience. I'll send you the finalized proposal by Wednesday, no extensions after that.",
      },
      {
        label: "Firm",
        icon: "⚡",
        text: "I'm finalising two other deals this week. Can we lock in the terms today so I can prioritise accordingly?",
      },
    ],
  },
  {
    input:
      'The clause at section 4.2 states "at the landlord\'s sole discretion with 30 days notice"',
    type: "Contract Reader",
    power: 20,
    intent:
      "HIGH RISK clause. Sole discretion = total control for landlord. 30 days is insufficient for business relocation. This clause heavily favours the landlord.",
    emotion: ["Risk", "Imbalance", "Urgency"],
    manipulation: ["One-sided Power", "Inadequate Notice Period"],
    strategies: [
      {
        label: "Negotiate",
        icon: "📋",
        text: "Request minimum 90-day notice. Add 'landlord must provide written reason' and cap discretion to specific breach scenarios.",
      },
      {
        label: "Counter",
        icon: "⚖️",
        text: "At the landlord's discretion, subject to 90 days written notice and limited to cases of material breach by tenant.",
      },
      {
        label: "Walk Away",
        icon: "🚪",
        text: "If landlord refuses any modification to this clause, treat it as a red flag. Seek alternate premises.",
      },
    ],
  },
  {
    input:
      "I loved your pitch! We're definitely interested. Can you send pricing?",
    type: "Cold Outreach Scorer",
    power: 55,
    intent:
      "Genuine interest, but 'send pricing' = price-shopping mode. They want to compare. Don't just send a sheet – qualify before pricing.",
    emotion: ["Excitement", "Curiosity", "Buying Intent"],
    manipulation: [],
    strategies: [
      {
        label: "Qualify First",
        icon: "🎯",
        text: "Thanks! Before I send pricing – what's your timeline and which features matter most? Want to make sure I send the right package.",
      },
      {
        label: "Value Anchor",
        icon: "💡",
        text: "Happy to share pricing. Most clients invest ₹X–Y/month and see ROI in 60 days. Shall I schedule a 20-min demo first?",
      },
      {
        label: "Direct Send",
        icon: "📨",
        text: "Sending over our packages now. I'd recommend the Growth plan for your use case. Free trial available – want me to set one up?",
      },
    ],
  },
];

export const RB_HISTORY = [
  {
    id: "h1",
    date: "Apr 20, 2026",
    type: "Email Analyser",
    preview: "Thread: Q4 vendor contract renewal…",
    score: 42,
    result: "Moderate leverage. Vendor is pushing for a rate hike.",
  },
  {
    id: "h2",
    date: "Apr 19, 2026",
    type: "WhatsApp Analyser",
    preview: "Hey bhai, aaj meeting hai kya?",
    score: 70,
    result: "Genuine friendly inquiry. No hidden agenda.",
  },
  {
    id: "h3",
    date: "Apr 18, 2026",
    type: "Message Analyser",
    preview: "We need to revisit the terms discussed…",
    score: 28,
    result: "Adversarial tone. Prepare for renegotiation.",
  },
  {
    id: "h4",
    date: "Apr 17, 2026",
    type: "Contract Reader",
    preview: "Section 8: Termination clause states…",
    score: 15,
    result: "HIGH RISK. One-sided termination rights.",
  },
  {
    id: "h5",
    date: "Apr 16, 2026",
    type: "Cold Outreach Scorer",
    preview: "Hi, I wanted to reach out about your…",
    score: 62,
    result: "Above average. Add specific personalisation.",
  },
];

export const ANALYTICS = {
  monthlyReferrals: [28, 34, 41, 38, 52, 47, 61, 58, 72, 68, 85, 79],
  monthlyMembers: [380, 392, 401, 418, 435, 449, 462, 478, 492, 508, 524, 541],
  topReferrers: [
    { name: "Rajesh Gupta", count: 89, value: "₹42L" },
    { name: "Anita Rao", count: 67, value: "₹31L" },
    { name: "Priya Sharma", count: 54, value: "₹24L" },
    { name: "Vikram Singh", count: 48, value: "₹38L" },
    { name: "Arjun Mehta", count: 42, value: "₹18L" },
  ],
  conversionRate: 34,
  renewalRate: 87,
  dau: 1240,
  churnRate: 8,
};

export const HQ_DATA = {
  totalCities: 28,
  totalChapters: 142,
  activeMembers: 12480,
  mrr: 18500000,
  arr: 222000000,
  renewalRate: 87,
  growth: 23,
  bizGenerated: 680000000,
  cityBreakdown: [
    { city: "Mumbai", chapters: 12, members: 1480, revenue: "₹2.4Cr" },
    { city: "Delhi", chapters: 18, members: 2100, revenue: "₹3.8Cr" },
    { city: "Bangalore", chapters: 10, members: 1240, revenue: "₹2.1Cr" },
    { city: "Hyderabad", chapters: 8, members: 980, revenue: "₹1.6Cr" },
    { city: "Chennai", chapters: 7, members: 840, revenue: "₹1.4Cr" },
    { city: "Pune", chapters: 9, members: 1020, revenue: "₹1.7Cr" },
    { city: "Ahmedabad", chapters: 11, members: 1180, revenue: "₹1.9Cr" },
    { city: "Jaipur", chapters: 5, members: 560, revenue: "₹0.9Cr" },
  ],
};
